language: python
python:
  - "3.12"

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - coverage report -m

after_success:
  - coveralls

branches:
  only:
    - main
